// src/icons/lucide-shim.js
export { default as Briefcase }     from 'lucide-react/icons/briefcase'
export { default as Mail }          from 'lucide-react/icons/mail'
export { default as Lock }          from 'lucide-react/icons/lock'
export { default as User }          from 'lucide-react/icons/user'

export { default as HelpCircle }    from 'lucide-react/icons/help-circle'
export { default as Save }          from 'lucide-react/icons/save'
export { default as MapPin }        from 'lucide-react/icons/map-pin'
export { default as Building2 }     from 'lucide-react/icons/building-2'
export { default as Users }         from 'lucide-react/icons/users'
export { default as DoorOpen }      from 'lucide-react/icons/door-open'
export { default as LayoutGrid }    from 'lucide-react/icons/layout-grid'
export { default as Monitor }       from 'lucide-react/icons/monitor'
export { default as Presentation }  from 'lucide-react/icons/presentation'
export { default as Beaker }        from 'lucide-react/icons/beaker'
export { default as Crosshair }     from 'lucide-react/icons/crosshair'
export { default as ShieldCheck }   from 'lucide-react/icons/shield-check'
export { default as Info }          from 'lucide-react/icons/info'
export { default as ExternalLink }  from 'lucide-react/icons/external-link'
export { default as LocateFixed }   from 'lucide-react/icons/locate-fixed'
export { default as Eraser }        from 'lucide-react/icons/eraser'
